x = int(input('Escreva um número: '))
print('___'*12)
print(f'A tabuada do número {x} é =\n1 x {x} = {x*1}\n2 x {x} = {x*2}\n3 x {x} = {x*3}\nDo 4 é= {x*4}\nDo 5 é= {x*5}')
print(f'Do 6 é= {x*6}\nDo 7 é= {x*7}')
print('___'*12)
