-- CHAVE PRIMARIA
-- É O "ID" DE UMA LINHA OU COLUNA IU GRUPO DE COLUNAS = FEITO POR MEIO DE RESTRIÇOES  - CONSTRAINTS 

CREATE TABLE nome_Tabela (
	nomeColuna tipoDeDados PRIMARY KEY
	nomeColuna tipoDeDados ...
)

--CHAVE ESTRANGEIRA 
-- É DEFINIDA EM UMA TABELA - CHAMADA DE FILHO, É APENAS UMA REFERENCIA PARA IR A TABELA INICIAL PRA BUSCAR INFORMAÇÃO
-- É DEFINIDA ATRAVES DE "FOREIGN KEY CONTRAINT"
-- ELA MANTEM A INTEGRIDADE REFERENCIAL - DADOS ESTAVEIS